name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies (Linux only)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk xvfb

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest

    - name: Start virtual display (Linux only)
      if: matrix.os == 'ubuntu-latest'
      run: |
        echo "DISPLAY=:99.0" >> $GITHUB_ENV
        Xvfb :99 -screen 0 1024x768x24 &
        sleep 3

    - name: Run tests (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        xvfb-run -a python -m pytest tests/ -v

    - name: Run tests (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        python -m pytest tests/ -v
