name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install system dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk
        
    - name: Install pytest
      run: |
        python -m pip install pytest
    
    - name: Set up virtual display (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install -y xvfb
        echo "DISPLAY=:99.0" >> $GITHUB_ENV
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    
    - name: Run tests
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          xvfb-run python -m pytest tests/ -v
        else
          python -m pytest tests/ -v
        fi